# config.yaml for uav_mavlink

# Section 1: rates for polling HIGHRES_IMU and ATTITUDE_QUATERNION
# Recommended for VINS Mono, 100Hz
mavlink_rate: 100

# Section 2: link between ardupilot and uav_mavlink
# "uart"  --> UART
# "udpc"  --> UDP Client
# "udps"  --> UDP Server
# "split" --> splitter, which is used for time critical image&imu sync data
mavlink_activate: "split"

# Section 3: drone links
# Currently, there is only one link, dual link might be considered for backup.
# Please check above activated link.
uav_com:
  - type: "uart"
    path: "/dev/ttyUSB0"
    baud: 921600
  - type: "udps"
    port-s: 14560
  - type: "udpc"
    port: 14550
    addr: "192.168.1.15"
  - type: "split"
    port-s: 5400
    port: 5600
    addr: "127.0.0.1"
    clock: 95000
    sync: 50
    frame: 15
    threshold: 10

# Section 4: IPC links between VINS Mono/Fusion, ego-planner and uav_mavlink
# "ipc1" --> for att_pos_mocap/vision_speed_estimate 
# "ipc2" --> for MAV_FRAME_BODY_OFFSET_NED commands
ipcs:
  - type: "ipc1"
    path: "/tmp/uav_server"
  - type: "ipc2"
    path: "/tmp/uav_server2"

# Section 5: ROS topic for IMU data/IMG time
uav_imu: "/tmp/uav_imu"
uav_img: "/tmp/uav_img"

# Section 6: debug
debug: false
