# config.yaml for uav_camera

# Section 1: image latency from camera to uav_camera
img_latency: 50

# Section 2: image source, csi://0 or rtp://@:5400
img_source: "rtp://@:5600"

# Section 3: ROS topic for IMU data
img_topic: "/tmp/uav_cam0"
tim_topic: "/tmp/uav_img"

uav_imu: "/tmp/uav_imu"

# Section 4: debug
debug: false