# config.yaml for uav_mavlink

mavlink_activate: "udpc"  # "uart", "udpc", "udps"
mavlink_rate: 200     # 200Hz

# Drone communication:
uav_com:
  - type: "uart"
    path: "/dev/ttyUSB0"
  - type: "udps"
    port: 14560
  - type: "udpc"
    port: 14550
    addr: "192.168.1.15"

# IPC settings:
ipcs:
  - type: "ipc1"
    path: "/tmp/uav_server"
  - type: "ipc2"
    path: "/tmp/uav_server2"

# ROS topic
uav_imu: "/tmp/uav_imu"

debug: false
