# config.yaml for uav_camera

# Section 1: image latency from camera to uav_camera
#img_latency: 50

# Section 2: camera source/ros topic
cam_source:
  - type: "input"
    source: "rtp://@:5700"
    decoder: "--input-decoder=v4l2"
    codec: "--input-codec=h265"
    tim: "/tmp/uav_tim0"
    imu: "/tmp/uav_imu"
  - type: "output"
    cam: "/tmp/uav_cam0"

# Section 3: enable splitter support
enable_split: true

# Section 4: debug
enable_debug: false